In [1]:
!pip install numpy

In [53]:
import numpy as np
x = np.array([1,2,3,4,5]) #1D ARRAY
print(x)
b = x[1:2] #Acess 2
print(b)
print(x[-3:-1])
print(x[1:5:2])

[1 2 3 4 5]
[2]
[3 4]
[2 4]


In [55]:
y = np.array([[1,2,3],
              [4,5,6]])#2D ARRAY
print(y)
a = y[0,1:2] # Access 2
print(a)

[[1 2 3]
 [4 5 6]]
[2]


In [59]:
z = np.array([[[1,2,3],
             [4,5,6]],
            [[5,6,7],
             [4,5,6]]])#3D ARRAY
print(z)
c = z[1,1,1] #Access 5
print(c)
print(z.ndim) #To know the dimensions 

[[[1 2 3]
  [4 5 6]]

 [[5 6 7]
  [4 5 6]]]
5
3


In [61]:
a = np.array([1,2,3,4])
print(a.dtype)

int32


In [63]:
a = np.array([1,2,3,4],dtype='S')
print(a)
print(a.dtype)

[b'1' b'2' b'3' b'4']
|S1
